### ISSUE TITLE
Matching an exact route, not a pattern

### ISSUE THREAD

**Issue by csillag** [pbastowski/dev-proxy#1]
I have a question.

What if I would like to proxy `/foo`, but not `/foo/bar` ?
In other words, how do I tell the pattern recognizer not to interpret the source parameter as a pattern,
but as a string that must be an exact match?

Thanks.

**Comment by pbastowski** [comment]
@csillag I have pushed v0.0.4 which should address your request. See the updated [README](https://github.com/pbastowski/dev-proxy#usage)

Does this help?

**Comment by csillag** [comment]
Thanks, but I realizes that I will need a lot more custom functionality, so
I'm the end I forked your code. Thank you anyway.
